services:
  backend:
    build: ./backend
    container_name: fastapi
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://avautomation01_db_user:OW72dD6yUynHHCzo@cluster0.s40plbc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  frontend:
    build: ./frontend
    container_name: react
    ports:
      - "80:80"
    depends_on:
      - backend

  init-db:
    build: ./backend
    command: ["python", "database.py"]
    environment:
      - MONGO_URI=mongodb+srv://avautomation01_db_user:OW72dD6yUynHHCzo@cluster0.s40plbc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - backend

# MongoDB service removed because you are using Atlas
# volumes:
#   mongo_data: